/**
 * Copyright (C) 2014  MudRaker
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as 
 * published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty 
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 */
// Date: 16/03/2014 2:23:44 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package org.mudraker.ruler;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class RulerMarkerModel extends ModelBase
{
  //fields
    ModelRenderer Base;
    ModelRenderer Stem;
    ModelRenderer Cap;
    ModelRenderer Flag;
  
  public RulerMarkerModel()
  {
	  textureWidth = 64;
	  textureHeight = 32;
    
      Base = new ModelRenderer(this, 9, 0);
      Base.addBox(-3F, 0F, -3F, 6, 2, 6);
      Base.setRotationPoint(0F, 22F, 0F);
      Base.setTextureSize(64, 32);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      
      Stem = new ModelRenderer(this, 0, 0);
      Stem.addBox(-1F, -13F, -1F, 2, 13, 2);
      Stem.setRotationPoint(0F, 22F, 0F);
      Stem.setTextureSize(64, 32);
      Stem.mirror = true;
      setRotation(Stem, 0F, 0F, 0F);
      
      Cap = new ModelRenderer(this, 9, 9);
      Cap.addBox(-2F, -14F, -2F, 4, 1, 4);
      Cap.setRotationPoint(0F, 22F, 0F);
      Cap.setTextureSize(64, 32);
      Cap.mirror = true;
      setRotation(Cap, 0F, 0F, 0F);

      Flag = new ModelRenderer(this, 0, 16);
      Flag.addBox(0F, -12.5F, 1F, 1, 6, 6);
      Flag.setRotationPoint(-0.5F, 22F, 0F);
      Flag.setTextureSize(64, 32);
      Flag.mirror = true;
      setRotation(Flag, 0F, 0F, 0F);

  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Base.render(f5);
    Stem.render(f5);
    Cap.render(f5);
    Flag.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
